### ISSUE TITLE
Homepage: Use YTT instead of envsubst

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#106]
Configure a dashboard to be used in the d.rymcg.tech_homepage-template repo. Have link to d.ry in github, and other common services,  widgets, and links that might be useful for d.ry. include a background image.

**Comment by EnigmaCurry** [comment]
the default .env-dist has this repo : https://github.com/enigmacurry/d.rymcg.tech_homepage-template 

I believe you have the rights to commit there

**Comment by mcmikemn** [comment]
The new goal is to integrate Homepage more tightly with d.ry by having the default/template dashboard automatically configured with installed d.ry apps. 

- Makefile can detect installed d.ry apps in the same Docker context and ask the user if they want to configure them for Homepage
- Use `ytt` instead of `envsubst` in start.sh so we can have templating logic in the .yaml files
