### ISSUE TITLE
`make shell` doesn't work with instances

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#110]
When I install a 2nd instance of an app and in the shell for that instance run `make shell`, I'm `docker exec -it`-ed into the container of the original instance.

**Comment by EnigmaCurry** [comment]
`make shell` is implemented haphazardly for each container, I would like to make it centralized so its uniform for all, but that work needs to be done in #28.

**Comment by EnigmaCurry** [comment]
I have crossreferenced this and am closing as duplicate.
