### ISSUE TITLE
add authorization middlewares to go along with TFA

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#118]
Currently, you can install Gitea and use it for authentication, and if you install traefik-forward-auth and customize an app to use it, Gitea will require a login to access your app. But it will not affect what a successfully logged-in person can do in the app. If the app has built-in authentication/authorization and can check the user header that traefik-forward-auth sends, then the app can limit what the logged-in person can do in the app. But if the app can't check the user header, or if the app doesn't have built-in authentication/authorization at all, then any person with an account on your Gitea server can log into the app and have full access. And any user with an account on your Gitea server can log into **_all_** of your apps that have traefik-forward-auth configured, not just a select one or few.

One way to improve this is to add/create a middleware that receives the user header from traefik-forward-auth and compares it to a list of usernames that are allowed to log into the app; if the username from traefik-forward-auth is in the approved list, they can log into the app - if it isn't, they receive a 401. The list of approved usernames would be configurable in the app's .env file. The result would be that a user on your Gitea server could log into only those apps that are configured to allow them to log in; however, if those apps can't check the user header or don't have built-in authentication/authorization at all, then the user still has full access to the app once they're logged in. This might not be too big of a deal, because if an app doesn't have it's own internal authentication/authorization then there are no "permissions" to speak of - if you can use the app, you can use the app. But if an app does have it's own internal authentication/authorization but can't check the user header from traefik-forward-auth, then will all users who can log in have the same access?

**Comment by EnigmaCurry** [comment]
I think this can be done with a Traefik plugin like this: https://github.com/poloyacero/headauth

A plugin is a special kind of middleware that is builtin to Traefik, so like the blockpath and geoip plugins, this would be installed into traefik itself, and not require another middleware container to be started.

**Comment by EnigmaCurry** [comment]
I forked it here https://github.com/EnigmaCurry/traefik-header-authorization. I will test installing it in the traefik image.
