### ISSUE TITLE
More fixes for userns-remap needed.

### ISSUE THREAD

**Issue by EnigmaCurry** [EnigmaCurry/d.rymcg.tech#181]
The fix in #179 may have broken more stuff:

```
root@GPortable:~/git/vendor/enigmacurry/d.rymcg.tech# make userns-remap-off
## Checking Docker Daemon configuration (/etc/docker/daemon.json) ...
userns-remap setting not found
{}
scp: /tmp/tmp.3XObpr9LLc: No such file or directory
## Failure
## Checking Docker Daemon configuration (/etc/docker/daemon.json) ...
Not utilizing userns-remap
root@GPortable:~/git/vendor/enigmacurry/d.rymcg.tech# make userns-remap
## Checking Docker Daemon configuration (/etc/docker/daemon.json) ...
userns-remap setting not found
{
  "userns-remap": "default"
}
scp: /tmp/tmp.9yTJ26uUcu: No such file or directory
## Failure
## Checking Docker Daemon configuration (/etc/docker/daemon.json) ...
Not utilizing userns-remap
root@GPortable:~/git/vendor/enigmacurry/d.rymcg.tech#
```

_Originally posted by @ZarTek-Creole in https://github.com/EnigmaCurry/d.rymcg.tech/issues/179#issuecomment-1916459942_

**Comment by EnigmaCurry** [comment]
I haven't been able to reproduce this one yet @ZarTek-Creole 

https://github.com/EnigmaCurry/d.rymcg.tech/blob/f164887290a1751dcbbbb97333739e77747942b5/_scripts/userns-remap#L41-L46

It seems like it creates the temp file 41-44, and successfully cat the file on line 45. But then the file is missing on line 46? It doesn't behave like that for me. It works for me.

**Comment by ZarTek-Creole** [comment]
I apologize for any inconvenience. To confirm, I executed `git pull origin master` and retested. It is now functioning correctly. The problem seemed to stem from an error on my part. We can proceed to close the issue.

**Comment by EnigmaCurry** [comment]
Thanks for testing it! at least I am more confident it is really working now.
