### ISSUE TITLE
The Docker script `ntfy.sh` should perhaps be renamed to `ntfy`, as the dot in the Docker name makes it invalid.

### ISSUE THREAD

**Issue by ZarTek-Creole** [EnigmaCurry/d.rymcg.tech#187]
The Docker script [ntfy.sh](https://github.com/EnigmaCurry/d.rymcg.tech/tree/7a3aee57e1c86b4d913b66c49a8d39a0123271ac/ntfy.sh) should perhaps be renamed to `ntfy`, as the dot in the Docker name makes it invalid.

**Comment by EnigmaCurry** [comment]
Fixed in #207
