### ISSUE TITLE
Can `make wait` ignore config containers?

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#209]
When you run `make wait` for an app that has a config container, `make wait` continually waits for that config container to "finish starting". But I think config containers don't "start" - I think they just exist as data stores. Can `make wait` ignore any container with "config" in it's name?

**Comment by EnigmaCurry** [comment]
definitely a bug, I noticed it too. config containers do start, but they exit pretty quickly too, so the wait script is probably not accounting for the "done and stopped" state properly and it waits forever
