### ISSUE TITLE
`make status` when run from within an instance subshell, shows containers from all instances.

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#246]
When you're in an instance's subshel and you run `make status`, all of the app's containers in all instances are displayed.

**Comment by EnigmaCurry** [comment]
This is as designed. `make status` shows the status of all instances, regardless of whether your in the instance sub-shell or not. `make ps` is instance specific. If that is not implemented correctly, please re-open.
