### ISSUE TITLE
`tmp-context` isn't working

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#340]
If I use `d tmp-context` the old way (e.g. `d tmp-context <contextName>`,  a subshell is created and the name of the temporary context is show in PS1, but d.ry is still working with the main context.

E.g.: We enter a temp-context on the first line. Line 4 shows the tmp-context "dryt01" in PS1. We run `make config` and line 14 (the last line) shows d.ry is working on the main context "server01".
```
[root@drys01|G:9a5c290@(master)|D:server01|immich] $ d tmp-context
> Choose a temporary docker context dryt01
Entering sub-shell DOCKER_CONTEXT=dryt01
[@:dryt01] [root@drys01|G:9a5c290@(master)|D:server01|immich] $ make config
../_scripts/install_script-wizard
Looking for jq ... found /usr/bin/jq
Found supported OS: Linux
Found supported architecture: x86_64
script-wizard is already installed: /root/git/vendor/enigmacurry/d.rymcg.tech/_scripts/script-wizard
script-wizard version (installed): 0.1.34
Required locked version: 0.1.34
You already have the required version of script-wizard installed.

Configuring environment file: .env_server01_default
```

**Comment by EnigmaCurry** [comment]
Yea I reproduced it. Apparently DOCKER_CONTEXT is being set, but not exported.

If you run `export DOCKER_CONTEXT` it works as intended.
