### ISSUE TITLE
Invidious needs update to bypass Google's latest blocking method

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#355]
Invidious hadn't worked for me for a couple months, even with `make reinstall` (the image tag is "latest"). 

I found in [Invidious installation instructions](https://docs.invidious.io/installation/#docker-compose-method-production) that you now need to submit identifying tokens to Google.

If this works, it makes your instance/traffic more traceable - they mention they are working on an automation to change the tokens periodically, but this could probably be scripted into d.ry. Maybe instead of asking the user to create and enter tokens, they can be automatically created and used on eveery `make install`. Or maybe there's a way to automatically create new tokens every hour in the image and tell Invidious to use the new values?

**Comment by EnigmaCurry** [comment]
I would like to fix this, but I stopped playing videos in invidious long before they actually stopped working. (Why can't it play higher quality than 720p?) Anyway I still use invidious and its working for me, I just don't play the videos in the web browser, I use it as an API for searching and I just play with `mpv`.

**Comment by mcmikemn** [comment]
[This mvp](https://github.com/tbajkacz/mvp)?
