### ISSUE TITLE
Traefik is stuck in restarting loop.

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#359]
I wanted to add an entrypoint, layer7 route, and layer4 route, but traefik would not start up - it was constantly restarting with this repeating in the logs:
```
Waiting for config to be created ...
Found config: /data/config/traefik.yml
{"level":"error","error":"command traefik error: no configuration found in file: /data/config/traefik.yml","time":"2024-11-04T20:57:14Z","message":"Command error"}
```
 I deleted the entrypoint, layer7 route, and layer4 route and reinstalled, but with the same result.

`git bisect` told me [b3e1bb9495303a7f734e3718bd588751029f9121](https://github.com/EnigmaCurry/d.rymcg.tech/commit/b3e1bb9495303a7f734e3718bd588751029f9121) is the first bad commit.

It seems likely that you've been getting traefik to work since then, so perhaps some new code doesn't work with my specific configuration. E.g., I noticed that for the new entrypoint, layer7 route, and layer4 route that I created, there is a new "use_https" value, but all my existing entrypoints, layer7 routes, and layer4 routes don't have that value - perhaps a difference in tuples is causing the problem?

**Comment by EnigmaCurry** [comment]
We need to see what the traefik **config** container log says. The template is failing to render, and so I rigged Traefik to abort if it doesn't get a valid config rendered.

**Comment by EnigmaCurry** [comment]
Good bisecting skills, told me exactly the problem.
