### ISSUE TITLE
instance oddities in d.rymcg.tech

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#88]
After I create an instance and `<ctrl>-d` to return to the main shell, if I type `make switch`, d.rymcg.tech puts me in a subshell for the default instance - it doesn't ask me what instance I want to switch to. The same thing happens if I type `make switch <instance_name>`.

If I type `make instance`, d.rymcg.tech lists all instances of the projet and prompts me to enter one, then puts me in a subshell for that instance - this is great!

**Comment by EnigmaCurry** [comment]
It works this way: `make switch instance=foo`

**Comment by EnigmaCurry** [comment]
a bit more backstory: make doesn't allow positional arguments, it only allows named arguments. So any of these work and do the same thing:

`export INSTANCE=foo; make switch`
`INSTANCE=foo make switch`
`make INSTANCE=foo switch`
`make switch INSTANCE=foo`

`INSTANCE` and `instance` may be used interchangeably.

**Comment by mcmikemn** [comment]
Changed README to clarify in [PR #90](https://github.com/EnigmaCurry/d.rymcg.tech/pull/90)
