### ISSUE TITLE
`make instance` and `make switch` should optionally source ~/.bashrc

### ISSUE THREAD

**Issue by EnigmaCurry** [EnigmaCurry/d.rymcg.tech#89]
### Discussed in https://github.com/EnigmaCurry/d.rymcg.tech/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **mcmikemn** July 29, 2023</sup>
When you `make instance`, d.rymcg.tech creates a sub-shell for the new instance. Can that subshell retain or copy the environment from the main shell? For example, I have aliases set up in .bashrc in my main shell, but they're not available in the sub-shell.</div>

Because we cannot control what a user has in their ~/.bashrc it should not be the default behaviour to source it in the `make instance` subshell, however it might be nice to extend the environment by sourcing a select file by configuration.

A root environment variable like `MAKE_INSTANCE_SOURCE_RCFILE=` would be blank (or `/dev/null`) by default, but if you set this variable to a file path, it should source that file it before the other variables in the [make instance/switch](https://github.com/EnigmaCurry/d.rymcg.tech/blob/master/_scripts/Makefile.instance) script, thus extending the user's environment.

**Comment by mcmikemn** [comment]
I also just noticed that completion is only partial in subshells. I can type `d.r` and press the <tab> key and it autocompletes to `d.rymcg.tech` - which is good. But if I type `d.rymcg.tech con` and press <tab>, it does _not_ autocomplete to  `d.rymcg.tech context` like it does in the main shell.

**Comment by EnigmaCurry** [comment]
You just need to eval the completion code the same way as is in your .bashrc, so I think it will be solved by adding `MAKE_INSTANCE_SOURCE_RCFILE`:

```
export PATH=${PATH}:${HOME}/git/vendor/enigmacurry/d.rymcg.tech/_scripts/user
eval "$(d.rymcg.tech completion bash)"
```

**Comment by mcmikemn** [comment]
Oh, I see. Completeion isn't configured within d.ry, it's configured within my shell, and hence not (currently) in the subshell.

**Comment by mcmikemn** [comment]
I just pushed [6d793f7](https://github.com/EnigmaCurry/d.rymcg.tech/commit/6d793f7263e1a383fece4f20e75e3f61d3967d66), but it doesn't work yet. I'm struggling with the syntax to make the subshell source the file.

**Comment by EnigmaCurry** [comment]
open a pull request and i will review.
