### ISSUE TITLE
in homepage branch, `make destroy` fails to remove 1 container and thus 1 volume

### ISSUE THREAD

**Issue by mcmikemn** [EnigmaCurry/d.rymcg.tech#98]
I know this branch is under construction, but I wanted to add this issue before I forgot about it: when you `make destroy`, the config volume can't be destroyed because it's still in use:
```
✔ Container homepage-homepage-1  Removed
! Volume homepage_config         Resource is still in use 
✔ Network homepage_default       Removed 
```
`docker container ls | grep homepage` shows the container "homepage-homepage-run-c0314eb6dca9" still exists:
```
4e424d213162   fb94250c27a6                            "docker-entrypoint.s…"   45 hours ago   Exited (0) 45 hours ago                             homepage-homepage-run-c0314eb6dca9
```

**Comment by EnigmaCurry** [comment]
Probably need to add the `--rm` flag to this line https://github.com/EnigmaCurry/d.rymcg.tech/blob/034664a77b2a10314f5c28866a49f834cd831457/homepage/Makefile#L45

**Comment by EnigmaCurry** [comment]
I added it.
